version: "3.9"

services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - biz_network
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres-data:/data
      - ./postgres:/scripts:ro
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  init-db:
    image: postgres:${POSTGRES_IMAGE_TAG}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - biz_network
    volumes:
      - ./postgres:/scripts:ro
    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "PGPASSWORD=${POSTGRES_PASS} psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres -f /scripts/create_db.sql"

  biz:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - biz_network
    ports:
      - "${BIZ_PORT}:${BIZ_PORT}"
    restart: always

volumes:
  postgres-data:
    name: postgres-data
networks:
  biz_network:
    name: biz_network
