// Code generated by go-swagger; DO NOT EDIT.

package sql_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// SQLServiceGetUsersURL generates an URL for the SQL service get users operation
type SQLServiceGetUsersURL struct {
	AuthKey   *string
	MessageID *string
	UserID    *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SQLServiceGetUsersURL) WithBasePath(bp string) *SQLServiceGetUsersURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SQLServiceGetUsersURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SQLServiceGetUsersURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/users"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var authKeyQ string
	if o.AuthKey != nil {
		authKeyQ = *o.AuthKey
	}
	if authKeyQ != "" {
		qs.Set("authKey", authKeyQ)
	}

	var messageIDQ string
	if o.MessageID != nil {
		messageIDQ = *o.MessageID
	}
	if messageIDQ != "" {
		qs.Set("messageId", messageIDQ)
	}

	var userIDQ string
	if o.UserID != nil {
		userIDQ = *o.UserID
	}
	if userIDQ != "" {
		qs.Set("userId", userIDQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SQLServiceGetUsersURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SQLServiceGetUsersURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SQLServiceGetUsersURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SQLServiceGetUsersURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SQLServiceGetUsersURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SQLServiceGetUsersURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
