// Code generated by go-swagger; DO NOT EDIT.

package sql_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SQLServiceGetUsersHandlerFunc turns a function with the right signature into a SQL service get users handler
type SQLServiceGetUsersHandlerFunc func(SQLServiceGetUsersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SQLServiceGetUsersHandlerFunc) Handle(params SQLServiceGetUsersParams) middleware.Responder {
	return fn(params)
}

// SQLServiceGetUsersHandler interface for that can handle valid SQL service get users params
type SQLServiceGetUsersHandler interface {
	Handle(SQLServiceGetUsersParams) middleware.Responder
}

// NewSQLServiceGetUsers creates a new http.Handler for the SQL service get users operation
func NewSQLServiceGetUsers(ctx *middleware.Context, handler SQLServiceGetUsersHandler) *SQLServiceGetUsers {
	return &SQLServiceGetUsers{Context: ctx, Handler: handler}
}

/*
	SQLServiceGetUsers swagger:route GET /users SQLService sqlServiceGetUsers

SQLServiceGetUsers SQL service get users API
*/
type SQLServiceGetUsers struct {
	Context *middleware.Context
	Handler SQLServiceGetUsersHandler
}

func (o *SQLServiceGetUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSQLServiceGetUsersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
