// Code generated by go-swagger; DO NOT EDIT.

package sql_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SQLServiceGetUsersWithSQLInjectHandlerFunc turns a function with the right signature into a SQL service get users with Sql inject handler
type SQLServiceGetUsersWithSQLInjectHandlerFunc func(SQLServiceGetUsersWithSQLInjectParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SQLServiceGetUsersWithSQLInjectHandlerFunc) Handle(params SQLServiceGetUsersWithSQLInjectParams) middleware.Responder {
	return fn(params)
}

// SQLServiceGetUsersWithSQLInjectHandler interface for that can handle valid SQL service get users with Sql inject params
type SQLServiceGetUsersWithSQLInjectHandler interface {
	Handle(SQLServiceGetUsersWithSQLInjectParams) middleware.Responder
}

// NewSQLServiceGetUsersWithSQLInject creates a new http.Handler for the SQL service get users with Sql inject operation
func NewSQLServiceGetUsersWithSQLInject(ctx *middleware.Context, handler SQLServiceGetUsersWithSQLInjectHandler) *SQLServiceGetUsersWithSQLInject {
	return &SQLServiceGetUsersWithSQLInject{Context: ctx, Handler: handler}
}

/*
	SQLServiceGetUsersWithSQLInject swagger:route GET /users-with-sql-inject SQLService sqlServiceGetUsersWithSqlInject

SQLServiceGetUsersWithSQLInject SQL service get users with Sql inject API
*/
type SQLServiceGetUsersWithSQLInject struct {
	Context *middleware.Context
	Handler SQLServiceGetUsersWithSQLInjectHandler
}

func (o *SQLServiceGetUsersWithSQLInject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSQLServiceGetUsersWithSQLInjectParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
