CREATE TABLE IF NOT EXISTS "User" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    family VARCHAR(128) NOT NULL,
    age INTEGER CHECK (age > 0),
    sex INTEGER CHECK (sex IN (1, 0)),
    createdAt TIMESTAMPTZ DEFAULT NOW()
);