// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SQLInjectionUser sql injection user
//
// swagger:model sqlInjectionUser
type SQLInjectionUser struct {

	// age
	Age string `json:"age,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// family
	Family string `json:"family,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// sex
	Sex *SQLInjectionSex `json:"sex,omitempty"`
}

// Validate validates this sql injection user
func (m *SQLInjectionUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SQLInjectionUser) validateSex(formats strfmt.Registry) error {
	if swag.IsZero(m.Sex) { // not required
		return nil
	}

	if m.Sex != nil {
		if err := m.Sex.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sex")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sex")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sql injection user based on the context it is used
func (m *SQLInjectionUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSex(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SQLInjectionUser) contextValidateSex(ctx context.Context, formats strfmt.Registry) error {

	if m.Sex != nil {
		if err := m.Sex.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sex")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sex")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SQLInjectionUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SQLInjectionUser) UnmarshalBinary(b []byte) error {
	var res SQLInjectionUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
